### ISSUE TITLE
Establish safe branching / commit procedures

### ISSUE THREAD

**Issue by horizonbound0** [jknowles10/Marvel-Weather-App#17]

**Comment by horizonbound0** [comment]
Discovered when making a pull request we can select a specific branch for us to push to from local.

**Comment by horizonbound0** [comment]
Decided today in the team meeting that we would locally maintain a develop branch and branch off that local develop branch for each feature, then merge the finished feature into the local develop to push to origin develop. Then pull into main.

Also, be very vocal about when we push, so teammates can pull in changes.

**Comment by nhl1090** [comment]
We are also adding notes to our code to specify what we'll be working on. Communicating changes once we push.
